### ISSUE TITLE
4.4, 4.11, and 4.19 similarities, and standardizing personalization and text transformation

### ISSUE THREAD

**Issue by dpersing** [w3c/apa#98]
I'm curious about how 4.4 (personalization with a focus on symbols), 4.11 (signing of text descriptions), and 4.19 (customization of text for captions or subtitles) are split out. I think these are all getting at differently flavors of ways text-based content might be presented in an immersive environment, but focuses on one scenario for each.

I think it would be valuable to consider one requirement for text-based content personalization (language, symbols, signing, etc.), and one for text transformation (font size, font, etc.) for any scenario that has text or a text equivalent. For example, a user who wants text descriptions to be presenting in sign might also want captions presented the same way.

**Comment by RealJoshue108** [comment]
Thanks for the comment - it would certainly make it simpler if it were to come under some 'Guideline x' and the 4.4 (personalization with a focus on symbols), 4.11 (signing of text descriptions), and 4.19 (customization of text for captions or subtitles) , were implementation details. This could happen but for now there is a benefit to having them as seperate requirements as they are rather specific sets of requirements for different users needs.

**Comment by RealJoshue108** [comment]
Interesting suggestion - and we will discuss in RQTF

**Comment by RealJoshue108** [comment]
@dpersing  We discussed this in the Research Questions Task Force https://www.w3.org/2020/05/20-rqtf-minutes.html @sehollier will comment soon with a precis.

**Comment by sehollier** [comment]
Thank you for your comment. We discussed your points at our recent Research Questions Task Force meeting. 

Symbols can be a customisation of text, i.e. it is possible to interchange text with a representative symbol directly, but sign language is a translation rather than a customisation.
 
As such, sign language has to feature specific structure, syntax, movement and a different order to the text equivalent. It is also likely that the sign language would be an ongoing stream of translated content rather than symbols which in the use case would be more of a simplified replacement for a word or a small collection of words. 

Captions are also a separate requirement as they’re not presented as a customization or a translation, but rather a representation of the same language  There are also distinct disability groups applicable to each use case. 

While the points will remain separate, we will consider some wording improvements based on your useful feedback to better clarify these points but our consensus is to keep the points separate. 
If you have further input we are happy to hear it.
